apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-api-feed
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: frestomartvn/udagram-api-feed:latest
        imagePullPolicy: Always  
        resources:
          requests:            
            cpu: 250m
          limits:            
            cpu: 500m                      
        envFrom:
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
          - configMapRef:
              name: config-secret
        ports:
            - containerPort: 8080    
      restartPolicy: Always