apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: backend-feed
  labels: 
    app: backend-feed
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: backend-feed
  template: 
    metadata: 
      labels: 
        app: backend-feed
    spec: 
      containers: 
        - name: backend-feed
          image: frestomartvn/udagram-api-feed:latest
          imagePullPolicy: Always          
          resources:
            requests:  
              memory: "64Mi"          
              cpu: 250m
            limits:
              memory: "1024Mi"
              cpu: 500m                      
          envFrom:
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: env-config        
          ports: 
            - containerPort: 8080
      restartPolicy: Always      

        